In [0]:
import numpy as np
import tensorflow as tf
import h5py
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
h5f = h5py.File('/gdrive/My Drive/Colab Notebooks/Introduction to Neural Networks & Deep Learning/Data/SVHN_single_grey1.h5','r')

In [0]:
X_train = h5f['X_train'][:]
X_test = h5f['X_test'][:]
y_train = h5f['y_train'][:]
y_test = h5f['y_test'][:]

In [0]:
h5f.close()

In [6]:
X_train.shape

(42000, 32, 32)

In [7]:
y_train.shape

(42000,)

In [8]:
X_test.shape

(18000, 32, 32)

In [9]:
y_test.shape

(18000,)

In [0]:
# Creating a subset of train and test data for kmeans classifier (As running with the complete data is consuming a lot of time)

# Reshaping the data

X_train_2 = np.reshape(X_train,(42000,1024))
X_test_2 = np.reshape(X_test,(18000,1024))

In [11]:
X_train_2.shape

(42000, 1024)

In [0]:
# Taking subset of Training and testing data for KNN

X_train_3 = X_train_2[:3000]
X_test_3 = X_test_2[:1000]
y_train_2 = y_train[:3000]
y_test_2 = y_test[:1000]

In [0]:
# KNeighbors Classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5 , weights = 'distance')

In [14]:
knn.fit(X_train_3, y_train_2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='distance')

In [0]:
y_pred = knn.predict(X_test_3)

In [16]:
knn.score(X_test_3, y_test_2)

0.354

Ideally should have used grid search to fine tune the hyper parameters. But as it was consuming lot of time, manually checking the ideal n_neighbors

In [20]:
knn2 = KNeighborsClassifier(n_neighbors= 10 , weights = 'distance')
knn2.fit(X_train_3, y_train_2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='distance')

In [21]:
knn2.score(X_test_3, y_test_2)

0.369

In [22]:
knn3 = KNeighborsClassifier(n_neighbors= 20 , weights = 'distance')
knn3.fit(X_train_3, y_train_2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=20, p=2,
           weights='distance')

In [23]:
knn3.score(X_test_3, y_test_2)

0.38

In [24]:
knn4 = KNeighborsClassifier(n_neighbors= 30 , weights = 'distance')
knn4.fit(X_train_3, y_train_2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=30, p=2,
           weights='distance')

In [25]:
knn4.score(X_test_3, y_test_2)

0.349

In [26]:
knn5 = KNeighborsClassifier(n_neighbors= 25 , weights = 'distance')
knn5.fit(X_train_3, y_train_2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=25, p=2,
           weights='distance')

In [27]:
knn5.score(X_test_3, y_test_2)

0.353

From the above models it can be seen that higest accuracy (0.38) was with k =  20

In [0]:
# So using k = 20 to predict y

y_pred = knn3.predict(X_test_3)

In [29]:
# Confusion Matrix
from sklearn import metrics

print(metrics.confusion_matrix(y_test_2, y_pred))

[[46  9  2  1 18  4 16  6  5 10]
 [ 4 51  4  6  9  3  8  5  1  2]
 [ 0 12 30 10  5  3  4 12  2 14]
 [ 8 12  6 24  3  9  7  5  3  8]
 [ 3 15  5  6 48  2  4  5  2  6]
 [ 7 12  6 12  4 28 13  4  9 10]
 [14  5  5  4 12  5 31  1  6 11]
 [ 1 12 11  6  4  6  3 59  1  4]
 [12  4  3  1  7  8 20  4 28 13]
 [17 10  6  4  7  7 12  6  7 35]]


In [0]:
# Classification report
from sklearn.metrics import classification_report

In [31]:
print(classification_report(y_test_2, y_pred))

              precision    recall  f1-score   support

           0       0.41      0.39      0.40       117
           1       0.36      0.55      0.43        93
           2       0.38      0.33      0.35        92
           3       0.32      0.28      0.30        85
           4       0.41      0.50      0.45        96
           5       0.37      0.27      0.31       105
           6       0.26      0.33      0.29        94
           7       0.55      0.55      0.55       107
           8       0.44      0.28      0.34       100
           9       0.31      0.32      0.31       111

   micro avg       0.38      0.38      0.38      1000
   macro avg       0.38      0.38      0.38      1000
weighted avg       0.38      0.38      0.38      1000



Using CNN:

In [0]:
trainY = tf.keras.utils.to_categorical(y_train, num_classes=10)
testY = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [34]:
tf.keras.backend.clear_session()
#Initialize model, reshape & normalize data
model = tf.keras.models.Sequential()

#Reshape data from 2D (32,32) to 3D (32, 32, 1)
model.add(tf.keras.layers.Reshape((32,32,1),input_shape=(32,32,)))

#normalize data
model.add(tf.keras.layers.BatchNormalization())

Instructions for updating:
Colocations handled automatically by placer.


In [0]:

#Add first convolutional layer
model.add(tf.keras.layers.Conv2D(32, #Number of filters 
                                 kernel_size=(3,3), #Size of the filter
                                 activation='relu'))

#Add second convolutional layer
model.add(tf.keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))

#Add MaxPooling layer
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))

#Add third convolutional layer
model.add(tf.keras.layers.Conv2D(10,kernel_size=(1,1), activation='relu'))

#Add GlobalAveragePooling layer
model.add(tf.keras.layers.GlobalAveragePooling2D())

In [0]:
#Flatten the output
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.BatchNormalization())

#Dense layer
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Dense(100, activation='relu'))

#Add OUTPUT layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [0]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03, decay=0.001)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 32, 32, 1)         0         
_________________________________________________________________
batch_normalization_v1 (Batc (None, 32, 32, 1)         4         
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 10)        650       
_________________________________________________________________
global_average_pooling2d (Gl (None, 10)                0         
__________

In [39]:
#Train the model
model.fit(X_train,trainY,          
          validation_data=(X_test,testY),
          epochs=10,
          batch_size=32)

Train on 42000 samples, validate on 18000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
42000/42000 [==============================] - 14s 327us/sample - loss: 2.2004 - acc: 0.1812 - val_loss: 2.2352 - val_acc: 0.2151
Epoch 2/10
42000/42000 [==============================] - 10s 235us/sample - loss: 1.9767 - acc: 0.2800 - val_loss: 1.9264 - val_acc: 0.3083
Epoch 3/10
42000/42000 [==============================] - 10s 234us/sample - loss: 1.8249 - acc: 0.3484 - val_loss: 1.9727 - val_acc: 0.2944
Epoch 4/10
42000/42000 [==============================] - 10s 234us/sample - loss: 1.7197 - acc: 0.3960 - val_loss: 1.9030 - val_acc: 0.3319
Epoch 5/10
42000/42000 [==============================] - 10s 235us/sample - loss: 1.6508 - acc: 0.4210 - val_loss: 1.6642 - val_acc: 0.4158
Epoch 6/10
42000/42000 [==============================] - 11s 261us/sample - loss: 1.6014 - acc: 0.4428 - val_loss: 1.5961 - val_acc: 0.4474
Epoch 7/10
42000/42000 [==============================] 

In [40]:
# Final Train Loss & Accuracy
model.evaluate(X_train,trainY)

42000/42000 [==============================] - 3s 79us/sample - loss: 1.5228 - acc: 0.4694


[1.5227609132130941, 0.46942857]

In [41]:
# Final Validation Loss & Accuracy
model.evaluate(X_test,testY)

18000/18000 [==============================] - 1s 80us/sample - loss: 1.5521 - acc: 0.4619


[1.5520621138678656, 0.46194443]

In [0]:
predY = model.predict_classes(X_test)

In [48]:
# Confusion Matrix
from sklearn import metrics

print(metrics.confusion_matrix(y_test, predY))

[[1243   92    3   17   15   78   45   87   37  197]
 [  96 1173   20   58   81  102   37  155   38   68]
 [  31   88  678  151  123  163  110  260   61  138]
 [  32   94   52  753   23  301   55  101   82  226]
 [  78  317  139   67  544   86   54  367   58  102]
 [  49   70   34  176   21 1090   50   93   39  146]
 [ 257   75   67   41   41  292  390  114  177  378]
 [  90  161   24   32   56   64   24 1274    8   75]
 [ 150   86   39  111   27  197  210   71  487  434]
 [ 261  101   30  114   19  218  177  127   74  683]]


In [49]:
print(classification_report(y_test, predY))

              precision    recall  f1-score   support

           0       0.54      0.69      0.61      1814
           1       0.52      0.64      0.57      1828
           2       0.62      0.38      0.47      1803
           3       0.50      0.44      0.46      1719
           4       0.57      0.30      0.39      1812
           5       0.42      0.62      0.50      1768
           6       0.34      0.21      0.26      1832
           7       0.48      0.70      0.57      1808
           8       0.46      0.27      0.34      1812
           9       0.28      0.38      0.32      1804

   micro avg       0.46      0.46      0.46     18000
   macro avg       0.47      0.46      0.45     18000
weighted avg       0.47      0.46      0.45     18000



Comparing the accuracy scores and the classification report it is clear that the NN classifiers perform better than the traditional classifiers.

This is seen especially when CNN classifiers are used. Main reason for this is the ability of the CNN to retain the spatial information using filters. Whereas in traditional classifers this information is lost when the input data is reshaped to feed into the model.

One of the other advantages is ability to learn from the vast data in a shorter time compared to a traditional classifier

