# Standard Data Types (Numbers, String, List, Tuple, Dictionary)

In [3]:
import numpy as np
import pandas as pd

In [6]:
a=5
b=10.0

In [4]:
type(a)

int

In [7]:
type(b)

float

In [8]:
a=float(a)
type(a)

float

In [10]:
print('Value of a+b =', a+b)

Value of a+b = 15.0


In [11]:
num = 5
name = 'Anand'

In [12]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 5, and my name is: Anand


In [14]:
print('My number is %d, and my name is: %s' %(num,name))

My number is 5, and my name is: Anand


In [15]:
str1='Python'
str2='Learning'

In [16]:
str1 + str2

'PythonLearning'

In [18]:
str1 + ' ' + str2

'Python Learning'

In [38]:
s='i am learning python, this is my first class'

In [23]:
s1=s.upper()
s1

'I AM LEARNING PYTHON, THIS IS MY FIRST CLASS'

In [24]:
s1.lower()

'i am learning python, this is my first class'

In [25]:
s.title()

'I Am Learning Python, This Is My First Class'

In [21]:
s.capitalize()

'I am learning python, this is my first class'

In [29]:
s

'i am learning python, this is my first class'

In [30]:
s.count('i')

5

In [31]:
s.count('i',5)

4

In [32]:
s.find('python')

14

In [33]:
s[14:20]

'python'

In [39]:
s.islower()

True

In [41]:
s1.islower()

False

In [43]:
s1.isupper()

True

In [44]:
s.replace('python','statistics')

'i am learning statistics, this is my first class'

In [45]:
s.startswith('i am')

True

In [46]:
s.endswith('class')

True

# LIST and Tuple Data Types

In [50]:
d=[5,8,12.5,'Rajesh',15,'Nithya']

In [51]:
d[0]

5

In [54]:
d1=d[0:3]

In [53]:
d[-1]

'Nithya'

In [56]:
sum(d1)

25.5

In [57]:
d.append(25)

In [58]:
d

[5, 8, 12.5, 'Rajesh', 15, 'Nithya', 25]

In [59]:
d.insert(4,'Dinesh')

In [60]:
d

[5, 8, 12.5, 'Rajesh', 'Dinesh', 15, 'Nithya', 25]

In [61]:
d.pop()

25

In [62]:
d.pop(1)

8

In [63]:
d

[5, 12.5, 'Rajesh', 'Dinesh', 15, 'Nithya']

In [64]:
t=(5, 12.5, 'Rajesh', 'Dinesh', 15, 'Nithya') #Read only

In [66]:
type(t)

tuple

In [67]:
#SET data type
a={1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}
set(a)

{1, 2, 3}

In [68]:
r1={'Name':'Sudha','Age':34}
r2={'Name':'Ram','Age':37}


In [69]:
r1.keys()

dict_keys(['Name', 'Age'])

In [70]:
r1.values()

dict_values(['Sudha', 34])

In [72]:
r1['Name']='Vijay'

In [73]:
r1

{'Age': 34, 'Name': 'Vijay'}

# NUMPY ARRAY

In [74]:
g=np.arange(12)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
g1=np.array([12,9,2,10])

In [85]:
np.mean(g1)

8.25

In [87]:
np.arange(18,25)

array([18, 19, 20, 21, 22, 23, 24])

In [88]:
np.arange(18,30,2)

array([18, 20, 22, 24, 26, 28])

In [89]:
np.linspace(18,28,6)

array([18., 20., 22., 24., 26., 28.])

In [90]:
g[2::2]

array([ 2,  4,  6,  8, 10])

In [91]:
g2=np.arange(0,30,2)

In [92]:
g2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [93]:
g3=g2.reshape(3,5)
g3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [94]:
g3[0,:]

array([0, 2, 4, 6, 8])

In [95]:
g3[0,2:]

array([4, 6, 8])

In [96]:
g3[:,0]

array([ 0, 10, 20])

In [97]:
g3[:2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [98]:
g3[:2,:-1]

array([[ 0,  2,  4,  6],
       [10, 12, 14, 16]])

In [99]:
g3[2,::2]

array([20, 24, 28])

In [100]:
g3[g3>20] #Boolean Indexing

array([22, 24, 26, 28])

In [101]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
10 in g3 #membership operator

True

In [104]:
10 not in g3

False

# if,elif,else statements

In [5]:
if 1 < 2:
    print('first')
else:
    print('last')

first


In [6]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


# Usage of For-loops

In [105]:
d=np.arange(15,25)
d

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [106]:
for val in d:             #Mapping by Value
    print(val+100)

115
116
117
118
119
120
121
122
123
124


In [107]:
for i in np.arange(len(d)):  # Mapping by Index
    print(d[i]+200)

215
216
217
218
219
220
221
222
223
224


In [ ]:
#Iterating through 2-D array (mapping by value)
for row in g3:
    for val in row:
        print(val)
        print('done')

In [109]:
len(g3)

3

In [111]:
g3[1]

array([10, 12, 14, 16, 18])

In [ ]:
for i in np.arange(len(g3)):
    for j in np.arange(len(g3[i])):
        print(g3[i,j]+100)
        print('done')

In [119]:
g10=g
g10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
g10[5]=100

In [122]:
g

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11])

In [123]:
import copy
g10=copy.deepcopy(g)

In [124]:
g10[8]=200
g10

array([  0,   1,   2,   3,   4, 100,   6,   7, 200,   9,  10,  11])

In [125]:
g

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11])

In [126]:
n = 5
while n > 0:
    print(n)
    n=n-1
print('Done')

5
4
3
2
1
Done


In [127]:
n = 5
while n > 0:
    print(n)
    n=n-1
    if n==3:
        break
print('Done')

5
4
Done


# List Comprehension

In [10]:
out = []
for item in d:
    out.append(item**2)
print(out)

[225, 256, 289, 324, 361, 400, 441, 484, 529, 576]


In [11]:
[item**2 for item in d]

[225, 256, 289, 324, 361, 400, 441, 484, 529, 576]

In [134]:
res=[val for val in range(0,50) if val%2==0]

# User Defined Function

In [137]:
def my_square(x):
    return(x**2)

In [13]:
my_square(10)

100

In [128]:
def my_avg(num):
    s=sum(num)
    A=s/len(num)
    return A,s

In [131]:
res1,res2=my_avg(g)
res1

13.416666666666666

In [132]:
res2

161

# Usage of Lambda Expressions (Anonymous Functions)

In [15]:
sum = lambda x1,x2: x1+x2

In [16]:
sum(20,30)

50

# Usage of MAP & FILTER

In [136]:
seq = [1,2,3,4,5]

In [30]:
my_square(5)

25

In [141]:
result=[]
for val in seq:
    result.append(my_square(val))
result

[1, 4, 9, 16, 25]

In [142]:
list(map(my_square,seq))


[1, 4, 9, 16, 25]

In [143]:
list(map(lambda x: x**2,seq))

[1, 4, 9, 16, 25]

In [36]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

# 2D LIST

In [163]:
L=[[2,8,-5,4],[9,1,3,-7,6]]
type(L)

list

In [145]:
L[1]

[9, 1, 3, -7, 6]

In [146]:
L[1][:2]

[9, 1]

In [149]:
len(L)

2

In [148]:
#Iteratate over 2D List
for row in L:
    for val in row:
        print (val+100)
        print('done')

In [166]:
len(L)

2

In [173]:
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
for  row  in a:
    for  elem  in row:
        print (elem, end=' ')
    print()


1 2 3 4 
5 6 
7 8 9 


In [175]:
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]  #here len(a) will show 3 items (ie) number of rows
for  i  in range(len(a)):
    for  j  in  range(len(a[i])):
        print(a[i][j]+100, end=' ')
    print()


101 102 103 104 
105 106 
107 108 109 
